### PR TITLE
Add selectAllObjects func to StateManager and clear all items on load

### PR DESCRIPTION
**Pull request by obimax99**
Use deleteAllSelectedObjects function within StateManager to handle the issue of clearing the screen before loading a new automaton.

### CODE REVIEW

**Comment by obimax99** [comment]
Could've sworn there was a way to add issues to PRs or vice versa but I'm unable to find it. This PR relates to:
["Current automaton not cleared when another automaton is loaded #84"](https://github.com/AutomatonBuilderGUI/AutomatonBuilderGUI/issues/84)

**Comment by Meorge** [comment]
I believe you can simply do it by writing the ID of the issue like so: #84 
Similarly, you can use the ID of a PR to link to it: #117 

I'll be able to look over this a little later tonight and get it merged if everything looks good! 😄

**Comment by Meorge** [comment]
Thanks for the PR! I think there may be a few things this needs yet:
- The action stack needs to be cleared when the new automaton is loaded. Currently we can see all of the deletion actions that occur as part of the loading action show up in the action stack.
- The alphabet needs to be reset when the new automaton is loaded. Currently, the new automaton's alphabet is appended to the current alphabet, so we can end up with repeat tokens.
  - This is out of scope for this feature, but in testing this I see that the GUI doesn't put up an error for duplicate tokens. I'll add this as an issue to the issue tracker.

Once those things are fixed, I think this should be ready to merge. The "select all" function is a great idea, and I think in a future PR we can add in a keyboard shortcut for the user to take advantage of that! 😄

**Comment by Meorge** [comment]
With #120 merged, there is a method `StateManager.clearMachine` that could be used to empty the current automaton state. It may make sense to sync your fork with the main repository, merge its current state into your branch, then use that method instead of redefining the same behavior.

**Comment by obimax99** [comment]
uh oh

**Comment by obimax99** [comment]
@Meorge Any idea how to revert? I thought I was grabbing info from here and into my fork, but that is not what happened I believe

**Comment by Meorge** [comment]
@obimax99 It sounds to me like what you might want to do is create a new branch on your repository set to commit `9c61115e9890150c9d18da57aee9d7374a0cc35e` (which has your changes). I think the command would be something like
```
git branch -f clear-items-on-load 9c61115e9890150c9d18da57aee9d7374a0cc35e
```
Then, you can merge the `main` branch into `clear-items-on-load`.

**Comment by obimax99** [comment]
There was the force push though, I'm not sure exactly what it affected.

**Comment by Meorge** [comment]
My understanding is that the force push basically just got the commits on the main repository and made your `main` branch use those. The commits you made for your feature PR are still in the repository itself, but they're no longer a part of any branch that has a tag attached to it, so there's no way to access them right now except by the commit ID. If we attach a new branch to that commit ID, then we can access those changes again.

**Pull request closed without merging**
