### PR TITLE
snap to grid feature finished

### PR DESCRIPTION
**Pull request by ttipton2**
finished the snap to grid feature for all zoom scales

### CODE REVIEW

**Comment by Meorge** [comment]
I can see the math for performing the snapping is included in the PR, but I don't see any way to enable or disable the functionality for the user. I think you might need to push changes to `index.tsx`?

**Comment by ttipton2** [comment]
here are the missing components

**Comment by Meorge** [comment]
Thanks for adding the button!

I just checked it out, and while it looks good overall, I see there is a visual bug where the transition arrows don't update to the snapped node position:

https://github.com/AutomatonBuilderGUI/AutomatonBuilderGUI/assets/9957987/32ae498a-8ec2-4198-841c-376a0ab6794e

Do you think it would be quick to fix this bug and then we could merge it in with the rest of the feature? Alternatively, we could merge in the basic behavior for now, and then open this bug as a new issue to fix.

**Comment by ttipton2** [comment]
That's weird because I totally thought I fixed it. It is a really easy fix, I just have to add the update start position to the spot after it's snapping. Hard to explain but easy to do. But yeah, when I get home I'll Check on it and see why that part didn't get committed.

Powered by Cricket Wireless
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request closed without merging**
